### ISSUE TITLE
Generate documentation for plugins automatically

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#475]
We might use [JSDoc](https://jsdoc.app/) and/or [Vuese](https://vuese.org). It would be good to export the documentation to [this wiki](https://github.com/ICIJ/datashare/wiki/). 

Stories:

* [x] configure JSDoc for the project
* [x] configure JSDoc with Vue components
* [x] write documentation for Core modules
* [x] write documentation for components
* [x] generate documentation for hooks
* [x] integrate documentation generation to CI
* [x] integrate documentation to Datashare's wiki
